# Generated by Django 4.2.7 on 2023-12-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='eventID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
